---
title: "0320-R_e_macroeconomia"
author: "R_para_Economistas"
date: "2/25/2020"
output: html_document
---

```{r setup, include=FALSE}
# install.packages(c("openssl", "httr", "rvest", "tidyverse", "ggfortify", "zoo", "kableExtra", "sidrar"))
library(openssl)
library(httr)
library(rvest)
library(tidyverse) # Conjunto de pacotes {ggplot2, dplyr, tidyr, readr, purrr, tibble, stringr, forcats}
library(ggfortify)
library(zoo)
library(forecast)
library(DT)
library(ggplot2)
library(sidrar)

theme_set(theme_classic())   # Todos os mapas virão com theme_classic() como default 
```

# Análise Macroeconomica com R Markdown

#### Este é um documento R Markdown, uma maneira simples de criar documentos dinâmicos em HTML, PDF, entre outros formatos.
Para mais detalhes, acesse <http://rmarkdown.rstudio.com> ou [Cheatsheet](https://rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)


```{r api_sidra, message=FALSE}
dados_sidra <- get_sidra(
  api = "/t/1846/n1/all/v/all/p/all/c11255/90707,93404,93405,93406,102880/d/v585%200")

```

Após feita a manipulação na base de dados, chegamos a um dataset como o seguinte:

```{r chunk2, echo=FALSE, message=FALSE}
cnt <- dados_sidra %>%
  select(`Setores e subsetores`, Trimestre, Valor) %>%
  rename(
    "setores" = `Setores e subsetores`, 
    "trimestre" = Trimestre,
    "valor" = Valor
  ) %>% 
  mutate(var = str_replace_all(
    setores, c("PIB a preços de mercado" = "PIB",
                              "Despesa de consumo das famílias" = "C",
                              "Despesa de consumo da administração pública" = "G",
                              "Formação bruta de capital fixo" = "FBKF",
                              "Variação de estoque" = "VE"))) %>%
  mutate(ano = as.integer(str_sub(trimestre, start = -4))) %>%
  mutate(tri = as.integer(str_sub(trimestre, end = 1))) %>%
  filter(ano >= 2000) %>%
  select(var, ano, tri, valor)

l_cnt <- split(cnt, cnt$var)

i_macro <- cbind(
  l_cnt$PIB["ano"],
  l_cnt$PIB["tri"],
  l_cnt$PIB["valor"],
  l_cnt$C["valor"],
  c(l_cnt$FBKF["valor"] + l_cnt$VE["valor"]),
  l_cnt$G["valor"]
)

names(i_macro) <- c("ano", "tri", "PIB", "C", "I", "G")

# Poderiamos representar o n de linhas hardcoded como a seguir
chained <- data.frame(PIB = rep(0, 80), C = rep(0, 80), I = rep(0, 80), G = rep(0, 80))
# mas seria mais interessante dinamizarmos o script para que futuras análises possam ser reproduzidas automaticamente
chained <- data.frame(PIB = rep(0, nrow(i_macro)), C = rep(0, nrow(i_macro)), I = rep(0, nrow(i_macro)), G = rep(0, nrow(i_macro)))

# Índice encadeado
for (i in 1:(nrow(i_macro)-4)) {
  chained$PIB[i+4] <- ((i_macro[i+4, "PIB"]-i_macro[i, "PIB"])/i_macro[i+4, "PIB"])*100
  chained$C[i+4] <- ((i_macro[i+4, "C"]-i_macro[i, "C"])/i_macro[i+4, "C"])*100
  # 2
  chained$I[i+4] <- ((i_macro[i+4, "I"]-i_macro[i, "I"])/i_macro[i+4, "I"])*100
  chained$G[i+4] <- ((i_macro[i+4, "G"]-i_macro[i, "G"])/i_macro[i+4, "G"])*100
}

dados_tsp <- ts(chained, start = c(i_macro$ano[1], i_macro$tri[1]), freq = 4)

dados_ts <- window(dados_tsp, start = c(2001, 1))    # Devido ao método encadeado, o ano de 2000 acaba sendo == 0

df_cnt <- data.frame(
  ano = rep(2000:2019, each=4),
  tri = rep(c(1:4), length.out = nrow(chained)),
  chained
)


DT::datatable(
  df_cnt, 
  caption = "R_para_Econmistas", 
  filter = 'top', 
  options = list(pageLength = 16, autoWidth = TRUE)
)
```



```{r chunk3, echo=FALSE, message=FALSE, fig.width=12, fig.height=8}

ggplot(dados_ts[, "PIB"], aes(seq(as.Date("2001/1/1"), by = "quarter", length.out = nrow(dados_ts))))+
  geom_line(aes(y = dados_ts[, "PIB"]), size = 1.1, color = "darkblue")+
  geom_line(aes(y = dados_ts[, "C"]), size = 1.1, color = "darkgreen")+
  geom_line(aes(y = dados_ts[, "I"]), size = 1.1, color = "cadetblue3")+
  geom_line(aes(y = dados_ts[, "G"]), size = 1.1, color = "red")+
  geom_hline(yintercept = mean(chained$I[5:length(chained$I)], na.rm = T), color = "cadetblue3", size = 1.05)+
  geom_hline(yintercept = 0, lty = "dashed")+
  labs(title = "Indicadores Macroeconomicos Brasileiros Encadeados",
       subtitle = paste0("Variáveis encadeadas com o mesmo trimestre do ano anterior de ",
                         i_macro$ano[1],
                         " à ",
                         i_macro$ano[nrow(i_macro)]),
       y = "% de variação encadeada com o trimestre do ano anterior",
       x = "",
       caption = "R_para_Economistas")+
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))

```
